### ISSUE TITLE
Blockquote cite difference in editor / frontend styles

### ISSUE THREAD

**Issue by saas786** [justintadlock/exhale#2]
Hi @justintadlock 

For some strange reasons

in editor **cite** is not used inside blockquote (at least in my install).

instead it applies this class in editor
**.wp-block-quote__citation**

where on frontend, I strangely get **cite** tag instead.

So maybe you want to use 
**.wp-block-quote__citation**

here https://github.com/justintadlock/exhale/blob/master/resources/scss/blocks/core/_quote.scss#L17

alongside **cite**

**Comment by justintadlock** [comment]
This should be addressed in 3.0.
