### ISSUE TITLE
`menu__item--parent` class added to blog page menu item when viewing Custom Post Type 

### ISSUE THREAD

**Issue by david-graham** [justintadlock/exhale#5]
- Set blog page to a static page
- Add this page to a menu
- View a custom post type archive or single
- Blog menu item will have `menu__item--parent` class

All the Hybrid Core `nav_menu_css_class` filter does is check if the `current_page_parent` class has been added to the menu item and replaces it with `menu__item--parent`.

Seems like a problem with WordPress core but a workaround might be needed.

**Comment by david-graham** [comment]
I meant to post this issue to the Hybrid Core repository, sorry. Too many tabs open.

**Comment by justintadlock** [comment]
Already a core ticket.  Closing in favor of that.

See: https://core.trac.wordpress.org/ticket/38486
