### ISSUE TITLE
PHP Warnings appear in front end and admin

### ISSUE THREAD

**Issue by skyshab** [justintadlock/exhale#6]
When activating Exhale 2.0 with WP_DEBUG enabled, I am seeing warnings/errors appear in the admin area and on the front end. 

In the admin area, this breaks the admin menu, causes issues on saving settings pages, etc.

<img width="1246" alt="Screen Shot 2019-07-15 at 5 38 01 AM" src="https://user-images.githubusercontent.com/1430876/61210924-a8108800-a6c3-11e9-9671-7ad059f0f2e2.png">

**Comment by justintadlock** [comment]
Dang, I didn't see that one because I'm always running a child theme where it doesn't show.
