### ISSUE TITLE
Editor Color replace pattern

### ISSUE THREAD

**Issue by saas786** [justintadlock/exhale#7]
You should change the order for pattern here
https://github.com/justintadlock/exhale/blob/master/app/Editor/Color/Color.php#L193

with this

```
		$pattern = [
			'lightest',
			'lighter',
			'light',
			'darkest',
			'darker',
			'dark',
		];

		$replace = [
			'100',
			'300',
			'400',
			'900',
			'700',
			'600',
		];
```

**Comment by justintadlock** [comment]
Already done in my dev copy, which I haven't pushed online yet, so I'm going to close this ticket.
